### ISSUE TITLE
It comes with 404 exception when there is no image file at imagePath url.

### ISSUE THREAD

**Issue by JmyW** [jitsm555/flutter_avatar_view#1]
Thank you for providing this package which makes easy to display an avatar. 
I found an issue that generated an exception if the image is not existed in server. 

The step:
1. Use AvatarView on ListView.build
2. Tap the listView item
3. Navigator.push(context, ... ) go into sub-page.

Then issue is happened with log below:

I/flutter (27025): CacheManager: Failed to download file from http://192.168.0.66/myserver/client_data/user/linda.jpg with error:
I/flutter (27025): HttpException: Invalid statusCode: 404, uri = http://192.168.0.66/myserver/client_data/user/linda.jpg

======== Exception caught by image resource service ================================================
The following HttpExceptionWithStatus was thrown resolving an image codec:
HttpException: Invalid statusCode: 404, uri = http://192.168.0.66/myserver/client_data/user/linda.jpg

When the exception was thrown, this was the stack: 
Image provider: CachedNetworkImageProvider("http://192.168.0.66/myserver/client_data/user/linda.jpg", scale: 1.0) 
 Image key: CachedNetworkImageProvider("http://192.168.0.66/myserver/client_data/user/linda.jpg", scale: 1.0): CachedNetworkImageProvider("http://192.168.0.66/myserver/client_data/user/linda.jpg", scale: 1.0)
====================================================================================================

**Comment by jitsm555** [comment]
Thanks for reporting, we will resolve soon.

**Comment by mrafsyam** [comment]
Hi, I still get the following error despite a valid URL to an image.

#### Code
```
AvatarView(
    radius: 60,
    borderWidth: 4,
    borderColor: AppColor.grey,
    avatarType: AvatarType.CIRCLE,
    backgroundColor: AppColor.greyColor,
    imagePath: "http://13.228.175.39:8000/images/avatar.png"
),
```
#### Error 
```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building Image(image: CachedNetworkImageProvider("http://13.228.175.39:8000/images/avatar.png", scale: 1.0), frameBuilder: Closure: (BuildContext, Widget, int?, bool) => Widget from Function '_placeholderBuilder@1025215462':., loadingBuilder: null, fit: cover, alignment: Alignment.center, this.excludeFromSemantics: false, filterQuality: low, dirty, dependencies: [MediaQuery, _EffectiveTickerMode, Directionality, _LocalizationsScope-[GlobalKey#87bc2]], state: _ImageState#26643(stream: ImageStream#92251(MultiImageStreamCompleter#0398c, unresolved, 2 listeners), pixels: null, loadingProgress: null, frameNumber: null, wasSynchronouslyLoaded: false)):
Null check operator used on a null value

The relevant error-causing widget was: 
  AvatarView file:///C:/Users/rafsy/Documents/personal_projects/mysangkar/mobile/lib/view/register/register.dart:71:15
When the exception was thrown, this was the stack: 
#0      CircularWidget.build.<anonymous closure> (package:avatar_view/circular_widget.dart:66:47)
#1      CachedNetworkImage._octoPlaceholderBuilder (package:cached_network_image/src/cached_image_widget.dart:288:24)
#2      ImageHandler._placeholder (package:octo_image/src/image/image_handler.dart:307:33)
#3      ImageHandler._placeholderBuilder (package:octo_image/src/image/image_handler.dart:232:16)
#4      _ImageState.build (package:flutter/src/widgets/image.dart:1312:36)
...
====================================================================================================

```
**Update : Version   avatar_view: 1.0.0+4**

**Comment by jitsm555** [comment]
are you sure those images are public?
